SplittingTabsToolWindow.close=Fechar
SplittingTabsToolWindow.moveTabLeft=Mover aba para a esquerda
SplittingTabsToolWindow.moveTabRight=Mover guia para a direita
SplittingTabsToolWindow.newTab=Nova guia
SplittingTabsToolWindow.renameTab=Renomear Guia